language: r
  r: 
    - devel
  cache: packages
  install:
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install_deps("R", dependencies = TRUE)'
    - cd R
    - R CMD build .
    - R CMD INSTALL *tar.gz
  script:
    - R -e 'library(fastquant); library(devtools); devtools::test()'